### ISSUE TITLE
Line no:-139

### ISSUE THREAD

**Issue by patelom693** [Cyanic76/discord-modmail#35] opened 2021-09-10 03:58 UTC
@Cyanic76 #34 
![Screenshot_2021-09-10-09-21-45-504_com android chrome](https://user-images.githubusercontent.com/84563189/132797588-a9a0dd31-4b83-4964-9d39-3f96abe5296b.jpg)

**Comment by Cyanic76** [comment] 2021-09-10 03:59
This is a duplicate of #34.

**Closed** 2021-09-10 04:00 UTC
